config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  match '/plants', as: 'plants', to: 'plants#index', via: :get
  match '/mosses', as: 'mosses', to: 'mosses#index', via: :get
  match '/fungi', as: 'fungi', to: 'fungi#index', via: :get
  match '/lichens', as: 'lichens', to: 'lichens#index', via: :get
  match '/algae', as: 'algae', to: 'algae#index', via: :get
  match '/fauna', as: 'fauna', to: 'fauna#index', via: :get
  match '/flora', as: 'flora', to: 'flora#index', via: :get
  get 'nsl', as: 'explicit_nsl', to: 'nsl#index', via: :get
  root 'nsl#index', as: 'nsl', via: :get
end

app/models/application_record.rb
# frozen_string_literal: true

# Check if used
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/algae_controller.rb
# frozen_string_literal: true

# Algae requests handled here.
class AlgaeController < ApplicationController
  private

  def set_zone
    @zone = 'algae'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Superclass for other controllers
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_zone

  private

  def set_zone
    @zone = ''
  end
end

app/controllers/fauna_controller.rb
# frozen_string_literal: true

# Fauna requests handled here.
class FaunaController < ApplicationController
end

app/controllers/flora_controller.rb
# frozen_string_literal: true

# Flora requests handled here.
class FloraController < ApplicationController
  private

  def set_zone
    @zone = 'flora'
  end
end

app/controllers/fungi_controller.rb
# frozen_string_literal: true

# Fungi requests handled here.
class FungiController < ApplicationController
  private

  def set_zone
    @zone = 'fungi'
  end
end

app/controllers/lichens_controller.rb
# frozen_string_literal: true

# Lichens requests handled here.
class LichensController < ApplicationController
  private

  def set_zone
    @zone = 'lichens'
  end
end

app/controllers/mosses_controller.rb
# frozen_string_literal: true

# Mosses requests handled here.
class MossesController < ApplicationController
  private

  def set_zone
    @zone = 'mosses'
  end
end

app/controllers/nsl_controller.rb
# frozen_string_literal: true

# NSL requests handled here.
class NslController < ApplicationController
  def index
  end
end

app/controllers/plants_controller.rb
# frozen_string_literal: true

# Plants requests handled here.
class PlantsController < ApplicationController
  private

  def set_zone
    @zone = 'plants'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# View utility methods
module ApplicationHelper
  def ticked(s)
    "#{s} #{fa_icon('check')}".html_safe
  end

  def env_tag
    case Rails.configuration.try('environment')
    when /^dev/i
      'Dev'
    when /^test/i
      'Test'
    when /^stag/i
      'Staging'
    when /^prod/i
      ''
    else
      'Unknown'
    end
  end
end

app/views/algae/_sidebar.html.erb
  <nav class="bd-links" id="docsNavbarContent">
    <div class="bd-toc-item active">
      <%= link_to "National Species Lists",
                  nsl_path,
                  class: "bd-toc-link",
                  title: "National Species Lists" %>
      <%= link_to "&ndash;&nbsp;Flora".html_safe,
                  flora_path,
                  class: "bd-toc-link",
                  title: "NSL Flora" %>
      <%= link_to ticked("&ndash;&ndash;&nbsp;Algae"),
                  algae_path,
                  class: "bd-toc-link active",
                  title: "National Species Lists - Algae" %>
    </div>
  </nav>

app/views/algae/index.html.erb
<% content_for :page_title do %>
  Algae
<% end %>
<% content_for :page_banner do %>
  <h1>Algae</h1>
<% end %>
<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

app/views/algae/search.html.erb
<h1>Apni#search</h1>
<p>Find me in app/views/apni/search.html.erb</p>

app/views/fauna/_sidebar.html.erb
  <nav class="bd-links" id="docsNavbarContent">
    <div class="bd-toc-item active">
      <%= link_to "National Species Lists",
                  nsl_path,
                  class: "bd-toc-link",
                  title: "National Species Lists" %>
      <%= link_to ticked("&ndash;&nbsp;Fauna"),
                  fauna_path,
                  class: "bd-toc-link",
                  title: "National Species Lists - Fauna" %>
    </div>
  </nav>

app/views/fauna/index.html.erb
<% content_for :page_title do %>
  NSL: Fauna
<% end %>
<% content_for :page_banner do %>
  <h1>Fauna</h1>
<% end %>

<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

<div class="row">
  <div class="col-xl-6 col-lg-8 col-md-9">
    <p>Currently delivered through the 
    <a href="https://biodiversity.org.au/afd/home">
      Australian Faunal Directory (AFD)
    </a>.
    </p>
  </div>
</div>

app/views/flora/_sidebar.html.erb
  <nav class="bd-links" id="docsNavbarContent">
    <div class="bd-toc-item active">
      <div id="sidebar-navigation-menu" class="">
      <%= link_to "National Species Lists",
                  nsl_path,
                  class: "bd-toc-link",
                  title: "National Species Lists" %>
      <%= link_to ticked("&ndash;&nbsp;Flora".html_safe),
                  flora_path,
                  class: "bd-toc-link",
                  title: "NSL Flora" %>
      </div>
        <hr>
        <ul class="nav bd-sidenav">
          <li class="">
            <%= link_to "Algae",
                        algae_path,
                        class: "",
                        title: "Algae" %>
          </li>
          <li class="">
            <%= link_to "Fungi",
                        fungi_path,
                        class: "",
                        title: "Fungi" %>
          </li>
          <li class="">
            <%= link_to "Lichens",
                        "#{Rails.application.config.lichen_search_url}",
                        class: "",
                        title: "Lichens" %>
          </li>
          <li class="">
            <%= link_to "Mosses",
                        "#{Rails.application.config.mosses_search_url}",
                        class: "",
                        title: "Mosses" %>
          </li>
          <li class="">
            <%= link_to "Vascular&nbsp;Plants".html_safe,
                        "#{Rails.application.config.plants_search_url}",
                        class: "",
                        title: "Vascular Plants" %>
          </li>
        </ul>
    </div>
  </nav>
  <br/>
  <span class="debug tiny hidden-print">[flora/_sidebar]</span>

app/views/flora/index.html.erb
<% content_for :page_title do %>
  NSL: Flora
<% end %>
<% content_for :page_banner do %>
  <h1>Flora</h1>
<% end %>

<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>


<div class="row">
  <div class="col-xl-7 col-lg-9 col-md-10">
<p>
This section of the National Species Lists infrastructure delivers names and
taxonomies for Australian native and naturalised organisms covered by the
International Code of Nomenclature for algae, fungi and plants (ICN). The
currently available data comprise names, bibliographic information, and
taxonomic concepts for these organisms.
</p>
<p>
Additional names and taxonomies will be accessible here as they become
available.
</p>
  </div>
</div>

app/views/fungi/_sidebar.html.erb
  <nav class="bd-links" id="docsNavbarContent">
    <div class="bd-toc-item active">
      <%= link_to "National Species Lists",
                  nsl_path,
                  class: "bd-toc-link",
                  title: "National Species Lists" %>
      <%= link_to "&ndash;&nbsp;Flora".html_safe,
                  flora_path,
                  class: "bd-toc-link",
                  title: "NSL Flora" %>
      <%= link_to ticked("&ndash;&ndash;&nbsp;Fungi"),
                  fungi_path,
                  class: "bd-toc-link active",
                  title: "National Species Lists - Fungi" %>
    </div>
  </nav>

app/views/fungi/index.html.erb
<% content_for :page_title do %>
  Fungi
<% end %>
<% content_for :page_banner do %>
  <h1>Fungi</h1>
<% end %>
<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

app/views/fungi/search.html.erb
<h1>Apni#search</h1>
<p>Find me in app/views/apni/search.html.erb</p>

app/views/layouts/_nav_links.html.erb
    <nav class="nav navbar-nav">
      <%= link_to("National Species Lists", explicit_nsl_path, class: "nav-item nav-link #{'active' if params[:controller].match(/nsl/)}", title: "Home page of the National Species Lists") %>
      <%= link_to("Flora", flora_path, class: "nav-item nav-link #{'active' if params[:controller].match(/flora/)}", title: "Home page of Flora National Species Lists") %>
      <%= link_to("Fauna", fauna_path, class: "nav-item nav-link #{'active' if params[:controller].match(/fauna/)}", title: "Home page of Fauna National Species Lists") %>
      <div class="text-xs-right">
        <%= link_to("Feedback", fauna_path, class: "xnav-item nav-link text-xs-right", title: "Home page of Fauna National Species Lists") %>
      </div>
      <span class="debug hidden-sm-up pull-right">xs &lt;544px</span>
      <span class="debug hidden-md-up hidden-xs-down pull-right">sm 544-767</span>
      <span class="debug hidden-lg-up hidden-sm-down pull-right">md 768-991</span>
      <span class="debug hidden-xl-up hidden-md-down pull-right">lg 992-1199</span>
      <span class="debug hidden-lg-down pull-right">xl 1200+</span>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>
    <%= env_tag %>&nbsp;<%= yield :page_title %>
  </title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png', :rel => 'shortcut icon' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
</head>

<body class="bd-docs <%= Rails.configuration.try('environment') %>" data-spy="scroll" data-target=".bd-sidenav-active" >
  <a id="skippy" class="sr-only sr-only-focusable" href="#content">
    <div class="container-fluid">
      <span class="skiplink-text">Skip to main content</span>
    </div>
  </a>
  <a id="top"></a>

  <header class="navbar navbar-light navbar-static-top bd-navbar">
    <div class="clearfix">
      <button class="navbar-toggler pull-xs-right hidden-sm-up" type="button" data-toggle="collapse" data-target="#bd-main-nav">
        &#9776;
      </button>
      <a class="navbar-brand hidden-sm-up" href="/">
        APNI/APC
      </a>
    </div>
    <div class="collapse navbar-toggleable-xs" id="bd-main-nav">
      <%= render 'layouts/nav_links' %>
    </div>
  </header>

<div id="wrapper">
  <div id="header" class="boa-pageheader <%= @zone %>">
    <div class="container-fluid print">
      <div class="left-page-edge-padding md-12 bd-content">
        <%= yield :page_banner %>
      </div>
    </div>
  </div>

  <div id="content">
    <div class="container-fluid">

      <% if @system_broadcast.present? && !@system_broadcast.match(/This is the test instance./) %> 
        <div class="row">
          <div class="col-xs-12 bd-content">
            <div id="broadcast">
              <%= @system_broadcast %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div class="no-left-padding col-md-3 col-xl-2 bd-sidebar">
          <div class="left-page-edge-sidebar-padding bd-sidebar hidden-print">
            <%= yield :sidebar %>
            <%= yield :slider %>
          </div>
        </div>
        
        <div class="col-md-9 bd-content">
          <%= yield %>
        </div>

      </div>

    </div>
  </div>

  <div id="footer" class="boa-footer text-muted hidden-print" role="contentinfo">
    <div class="container-fluid">
      <ul class="boa-footer-links">
        <li>
           <%= link_to "#{ fa_icon('chevron-left')} Back".html_safe, 'javascript:history.go(-1);', title: "Go back 1 page" %>
        </li>
        <li><a href="https://github.com/bio-org-au">GitHub</a></li>
        <li><a href="https://twitter.com/AuBiodiversity">Twitter</a></li>
      </ul>
      <p>Designed and built at the 
      <%= link_to("Australian National Botanic Gardens (ANBG)", "http://www.anbg.gov.au", title: "Australian National Botanic Gardens web page") %>.
      </p>
      <br/>
      <%= env_tag %>
    </div>
  </div>
</div>

</body>
</html>

app/views/lichens/_sidebar.html.erb
  <nav class="bd-links" id="docsNavbarContent">
    <div class="bd-toc-item active">
      <%= link_to "National Species Lists",
                  nsl_path,
                  class: "bd-toc-link",
                  title: "National Species Lists" %>
      <%= link_to "&ndash;&nbsp;Flora".html_safe,
                  flora_path,
                  class: "bd-toc-link",
                  title: "NSL Flora" %>
      <%= link_to ticked("&ndash;&ndash;&nbsp;Lichens"),
                  lichens_path,
                  class: "bd-toc-link",
                  title: "National Species Lists - Lichens" %>
    </div>
  </nav>

app/views/lichens/index.html.erb
<% content_for :page_title do %>
  Lichens
<% end %>
<% content_for :page_banner do %>
  <h1>Lichens</h1>
<% end %>
<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

app/views/lichens/search.html.erb
<h1>Apni#search</h1>
<p>Find me in app/views/apni/search.html.erb</p>

app/views/mosses/_sidebar.html.erb
  <nav class="bd-links" id="docsNavbarContent">
    <div class="bd-toc-item active">
      <%= link_to "National Species Lists",
                  nsl_path,
                  class: "bd-toc-link",
                  title: "National Species Lists" %>
      <%= link_to "&ndash;&nbsp;Flora".html_safe,
                  flora_path,
                  class: "bd-toc-link",
                  title: "NSL Flora" %>
      <%= link_to ticked("&ndash;&ndash;&nbsp;Mosses"),
                  mosses_path,
                  class: "bd-toc-link active",
                  title: "National Species Lists - Mosses" %>
    </div>
  </nav>

app/views/mosses/index.html.erb
<% content_for :page_title do %>
  Mosses
<% end %>
<% content_for :page_banner do %>
  <h1>Mosses</h1>
<% end %>

<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

app/views/mosses/search.html.erb
<h1>Apni#search</h1>
<p>Find me in app/views/apni/search.html.erb</p>

app/views/nsl/_sidebar.html.erb
  <nav class="bd-links" id="docsNavbarContent">
      <div class="bd-toc-item active">
        <div id="sidebar-navigation-menu" class="">
        <%= link_to ticked("National Species Lists"),
                    nsl_path,
                    class: "bd-toc-link",
                    title: "National Species Lists" %>
        </div>
        <hr>
        <ul class="nav bd-sidenav">
            <li class="">
              <%= link_to "Flora",
                          flora_path,
                          class: "",
                          title: "NSL Flora" %>
            </li>
            <li class="">
              <%= link_to "Fauna",
                          fauna_path,
                          class: "",
                          title: "NSL Fauna" %>
            </li>
        </ul>
      </div>
  </nav>

app/views/nsl/index.html.erb
<% content_for :page_title do %>
  National Species Lists
<% end %>

<% content_for :page_banner do %>
  <h1>National Species Lists</h1>
<% end %>

<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

<div class="row">
  <div class="col-xl-7 col-lg-9 col-md-10">

    <p>The National Species List infrastructure delivers names and taxonomies for Australian native and naturalised organisms. The currently available data comprise names, bibliographic information, and taxonomic concepts for those organisms covered by the International Code of Nomenclature for algae, fungi and plants (ICN) and the International Code of Zoological Nomenclature (ICZN).
    </p>
    
    <p>This infrastructure will provide the ability to search for names, nationally-accepted taxonomies (the National Species List), and other taxonomies where available. Currently searching is provided for vascular plants, liverworts, hornworts and mosses.
    </p>

    <p>This infrastructure is in continuous development and additional functionality and data will be accessible as they become available.
    </p>

<hr class="black-bg" />
  </div>
</div>

app/views/plants/_sidebar.html.erb
  <nav class="bd-links" id="docsNavbarContent">
    <div class="bd-toc-item active">
      <%= link_to "National Species Lists",
                  nsl_path,
                  class: "bd-toc-link",
                  title: "National Species Lists" %>
      <%= link_to "Flora",
                  flora_path,
                  class: "bd-toc-link",
                  title: "NSL Flora" %>
      <%= link_to ticked("Plants"),
                  plants_path,
                  class: "bd-toc-link active",
                  title: "National Species Lists - Plants" %>
    </div>
  </nav>

app/views/plants/index.html.erb
<% content_for :page_title do %>
  Mosses
<% end %>
<% content_for :page_banner do %>
  <h1>Mosses</h1>
<% end %>

<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

app/views/plants/search.html.erb
<h1>Apni#search</h1>
<p>Find me in app/views/apni/search.html.erb</p>